config/routes.rb
Rails.application.routes.draw do
  namespace :music do
    resources :year_in_reviews, only: [:index, :show] do
      member do
        get :top_albums
        get :top_songs
      end
    end
    
    resources :videos, only: [:index]
  end
  
  get 'music' => 'music/home#index', as: :music
end

app/controllers/music/home_controller.rb
class Music::HomeController < ApplicationController
  def index
    @user_name = Setting['home_page.apis.providers.lastfm.user_name']
    
    if Setting['home_page.apis.providers.lastfm.key'].present? && @user_name.present?
      @home_page_stylesheets = ['home_page/application', 'vendors/keen/dashboards']
      @home_page_javascripts = ['home_page/application', 'home_page_music/application']
      @body_class = 'application'
      
      [:recent_tracks, :artists, :releases, :tracks].each do |data_type|
        begin
          case data_type
          when :recent_tracks
            @recent_tracks = HomePageMusic::Api::LastfmRequest.new(
              :user, :get_recent_tracks, nil, user: @user_name, limit: 4, extended: 1
            ).response
          when :artists
            @artists = HomePageMusic::Api::LastfmRequest.new(
              :user, :get_top_artists, nil, user: @user_name, limit: 10
            ).response
          when :releases
            @releases = HomePageMusic::Api::LastfmRequest.new(
              :user, :get_top_albums, nil, user: @user_name, limit: 10
            ).response
          when :tracks
            @tracks = HomePageMusic::Api::LastfmRequest.new(
              :user, :get_top_tracks, nil, user: @user_name, limit: 10
            ).response
          end
        rescue StandardError => e
          ::Airbrake.notify e if Rails.env.production?
        end
      end
      
      @hide_footer = true
      
      render layout: 'fluid/without_rows'
    else
      flash[:alert] = t('general.apis.settings_missing', provider: 'last.fm') if user_signed_in?
      render text: '', layout: 'application'
    end
  end
end

app/controllers/music/videos_controller.rb
class Music::VideosController < ApplicationController
  before_filter :show_breadcrumbs, :volontariat_connection
  
  def index
    if @host.blank? || @user_id < 1
      flash[:alert] = I18n.t('general.apis.settings_missing', provider: 'Volontari.at') if user_signed_in?
      @videos = { 'entries' => [] }
    else
      begin
        @videos = JSON.parse(
          HTTParty.get("#{@host}/api/v1/users/#{@user_id}/library/music/videos.json?page=#{params[:page]}").body
        )
      rescue JSON::ParserError
      end
      
      if @videos.nil? || !@videos.has_key?('entries')
        flash[:alert] = I18n.t('general.apis.request_failed', provider: 'Volontari.at')
        @videos = { 'entries' => [] }
      else
        @pagination = HomePage::PaginationMetadata.new(@videos)
      end
    end
  end
  
  def resource
    @video
  end
  
  private
  
  def volontariat_connection
    @host = HomePage::ApiProviderHost.new('volontariat', Rails.env).to_s
    @user_id = Setting['home_page.apis.providers.volontariat.user_id']
  end
end

app/controllers/music/year_in_reviews_controller.rb
class Music::YearInReviewsController < ApplicationController
  before_filter :show_breadcrumbs
  
  before_filter :volontariat_connection
  
  def index
    if @host.blank? || @user_id < 1
      flash[:alert] = I18n.t('general.apis.settings_missing', provider: 'Volontari.at') if user_signed_in?
      @year_in_reviews = { 'entries' => [] }
    else
      begin
        @year_in_reviews = JSON.parse(
          HTTParty.get("#{@host}/api/v1/users/#{@user_id}/library/music/year_in_reviews.json?page=#{params[:page]}").body
        )
      rescue JSON::ParserError
      end
      
      if @year_in_reviews.nil? || !@year_in_reviews.has_key?('entries')
        flash[:alert] = I18n.t('general.apis.request_failed', provider: 'Volontari.at')
        @year_in_reviews = { 'entries' => [] }
      else
        @pagination = HomePage::PaginationMetadata.new(@year_in_reviews)
      end
    end
  end
  
  def show
    unless @host.blank? || @user_id.blank?
      begin
        @year_in_review = JSON.parse(
          HTTParty.get("#{@host}/api/v1/users/#{@user_id}/library/music/year_in_reviews/#{params[:id]}.json").body
        )
      rescue JSON::ParserError
      end
    end
    
    raise ActiveRecord::RecordNotFound if @year_in_review.nil?
  end
  
  def top_albums
    @home_page_javascripts = ['home_page/application', 'home_page_music/application']
    
    unless @host.blank? || @user_id.blank?
      @year_in_review = { 'year' => params[:id] }
      
      begin
        @albums = JSON.parse(
          HTTParty.get("#{@host}/api/v1/users/#{@user_id}/library/music/year_in_reviews/#{params[:id]}/top_releases.json").body
        )
      rescue JSON::ParserError
      end
    end
    
    raise ActiveRecord::RecordNotFound if @albums.nil?
  end
  
  def top_songs
    @home_page_javascripts = ['home_page/application', 'home_page_music/application']
    
    unless @host.blank? || @user_id.blank?
      @year_in_review = { 'year' => params[:id] }
      
      begin
        @songs = JSON.parse(
          HTTParty.get("#{@host}/api/v1/users/#{@user_id}/library/music/year_in_reviews/#{params[:id]}/top_tracks.json").body
        )
      rescue JSON::ParserError
      end
    end
    
    raise ActiveRecord::RecordNotFound if @songs.nil?
  end
  
  def resource
    @year_in_review
  end
  
  private
  
  def volontariat_connection
    @host = HomePage::ApiProviderHost.new('volontariat', Rails.env).to_s
    @user_id = Setting['home_page.apis.providers.volontariat.user_id']
  end
end

app/views/apis/lastfm/_chart_image_settings.html.erb
<div role="tabpanel">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a 
        href="#home_page_music_settings_apis_lastfm_recent_tracks_chart_image" 
        aria-controls="home_page_music_settings_apis_lastfm_recent_tracks_chart_image" role="tab" data-toggle="tab"
      >
        <%= t('settings.index.plugins.home_page_music.tabs.apis.lastfm.chart_images.recent_tracks.title') %>
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home_page_music_settings_apis_lastfm_recent_tracks_chart_image">
      <p>
        <%= setting_input f, 'home_page.apis.providers.lastfm.charts.types.recent_tracks.is_image' %>
        <%= setting_input f, 'home_page.apis.providers.lastfm.charts.types.recent_tracks.design' %>
        <%= setting_input f, 'home_page.apis.providers.lastfm.charts.types.recent_tracks.tracks_count' %>
      </p>
    </div>
  </div>
</div>

app/views/apis/lastfm/_settings.html.erb
<div role="tabpanel">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#home_page_music_settings_apis_lastfm_general" aria-controls="home_page_music_settings_apis_lastfm_general" role="tab" data-toggle="tab">
        <%= t('settings.index.plugins.home_page.tabs.general.title') %>
      </a>
    </li>
    <li role="presentation">
      <a href="#home_page_music_settings_apis_lastfm_chart_images" aria-controls="home_page_music_settings_apis_lastfm_chart_images" role="tab" data-toggle="tab">
        <%= t('settings.index.plugins.home_page_music.tabs.apis.lastfm.chart_images.title') %>
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home_page_music_settings_apis_lastfm_general">
      <p>
        <%= setting_input f, 'home_page.apis.providers.lastfm.user_name', label: t('general.apis.user_name'), required: true %>
        <%= setting_input f, 'home_page.apis.providers.lastfm.key', label: t('general.apis.key'), required: true %>
        <%= setting_input f, 'home_page.apis.providers.lastfm.secret', label: t('general.apis.secret'), required: true %>
      </p>
    </div>
    <div role="tabpanel" class="tab-pane" id="home_page_music_settings_apis_lastfm_chart_images">
      <p>
        <%= render partial: 'apis/lastfm/chart_image_settings', locals: { f: f } %>
      </p>
    </div>
  </div>
</div>

app/views/music/artists/_collection.html.erb
<% if (@artists || []).none? %>
<p><%= t('music.index.top_artists.none') %></p>
<% else %>
  <table class="table table-striped">
    <tbody>
    <% @artists.each do |artist| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td style="width:70px; text-align:right;">
          <%= image_tag (artist['image'] || []).select{|i| i['size'] == 'medium' }.first['content'] %>
        </td>
        <td style="width: 50px; text-align:right;"><%= artist['rank'] %></td>
        <td style="width: 100%;">
          <%= link_to artist['name'], artist['url'] %>
        </td>
        <td style="width: 50px; text-align:right;"><%= artist['playcount'] %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/music/home/index.html.erb
<% content_for :title do %>
  <%= t('music.index.title') %>
<% end %>

<div class="row">
  <div class="col-sm-6 col-md-4">
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="chart-wrapper">
      <div class="chart-stage" style="text-align:center; left:20%; width:275px;">
        <ul class="nav nav-pills">
          <li role="presentation"><a href="/music/year_in_reviews"><%= t('music.resources.year_in_review', count: 2) %></a></li>
          <li role="presentation"><a href="/music/videos"><%= t('general.liked', subject: 'Videos') %></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="chart-wrapper">
      <div class="chart-title">
        <%= t('music.index.recent_tracks.title') %>
      </div>
      <div class="chart-stage">
        <%= render partial: 'music/tracks/collection', locals: { tracks: @recent_tracks, recent: true } %>
      </div>
      <div class="chart-notes" style="text-align:center;">
        <%= link_to t('general.more'), "http://www.last.fm/user/#{@user_name}/tracks" %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="chart-wrapper">
      <div class="chart-title">
        <%= t('music.index.top_artists.title') %>
      </div>
      <div class="chart-stage">
        <%= render partial: 'music/artists/collection' %>
      </div>
      <div class="chart-notes" style="text-align:center;">
        <%= link_to t('general.more'), "http://www.last.fm/user/#{@user_name}/charts?rangetype=overall&subtype=artists" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="chart-wrapper">
      <div class="chart-title">
        <%= t('music.index.top_releases.title') %>
      </div>
      <div class="chart-stage">
        <%= render partial: 'music/releases/collection' %>
      </div>
      <div class="chart-notes" style="text-align:center;">
        <%= link_to t('general.more'), "http://www.last.fm/user/#{@user_name}/charts?rangetype=overall&subtype=albums" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="chart-wrapper">
      <div class="chart-title">
        <%= t('music.index.top_tracks.title') %>
      </div>
      <div class="chart-stage">
        <%= render partial: 'music/tracks/collection', locals: { tracks: @tracks } %>
      </div>
      <div class="chart-notes" style="text-align:center;">
        <%= link_to t('general.more'), "http://www.last.fm/user/#{@user_name}/charts?rangetype=overall&subtype=tracks" %>
      </div>
    </div>
  </div>
</div>

<% content_for :document_ready do %>
  window.volontariatHost = "<%= HomePage::ApiProviderHost.new('volontariat', Rails.env).to_s %>";
  new SpotifyPlayerList();
<% end %>

app/views/music/releases/_collection.html.erb
<% if (@releases || []).none? %>
<p><%= t('music.index.top_releases.none') %></p>
<% else %>
  <table class="table table-striped">
    <tbody>
    <% @releases.each do |release| %>
      <tr 
        class="spotify_player_list_item <%= cycle('odd', 'even') %>"
        data-model="Release" data-artist-name="<%= release['artist']['name'] %>" data-name="<%= release['name'] %>"
      >
        <td style="width:70px; text-align:right;">
          <%= image_tag (release['image'] || []).select{|i| i['size'] == 'medium' }.first['content'] %>
        </td>
        <td style="width: 50px; text-align:right;"><%= release['rank'] %></td>
        <td style="width: 100%;">
          <%= link_to release['artist']['name'], release['artist']['url'] %> – <%= link_to release['name'], release['url'] %>
        </td>
        <td style="width: 50px; text-align:right;"><%= release['playcount'] %></td>
        <td style="width: 50px; text-align:center;">
          <i class="hide spotify_player_list_item_play_icon glyphicon glyphicon-play" style="cursor:pointer; cursor:hand;"></i>
          <%= image_tag 'home_page/spinner.gif', class: 'spotify_player_list_item_spinner' %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/music/tracks/_collection.html.erb
<% recent ||= false %>

<% if (tracks || []).none? %>
<p><%= t('music.index.top_tracks.none') %></p>
<% else %>
  <table class="table table-striped">
    <tbody>
    <% tracks.each do |track| %>
      <tr 
        class="spotify_player_list_item <%= cycle('odd', 'even') %>" 
        data-model="Track" data-artist-name="<%= track['artist']['name'] %>" data-name="<%= track['name'] %>"
      >
      <% if recent %>  
        <td style="width:70px; text-align:right;">
          <%= image_tag (track['image'] || []).select{|i| i['size'] == 'medium' }.first['content'] %>
        </td>
      <% else %>
        <td style="width:50px; text-align:right;"><%= track['rank'] %></td>
      <% end %>
        <td style="width:100%;">
          <%= link_to track['artist']['name'], track['artist']['url'] %> – <%= link_to track['name'], track['url'] %>
        </td>
        <td style="width:50px; text-align:right;"><%= track['playcount'] %></td>
      <% if recent %>   
        <td style="width:100px; text-align:center; white-space:nowrap;">
        <% if track['nowplaying'] %>
          <%= t('music.index.recent_tracks.listening_now') %>
        <% else %>
          <%= DateTime.parse(track['date']['content']).strftime('%d.%m.%Y %H:%M') %>
        <% end %>
        </td>
      <% end %>
        <td class="list-element-striped" style="width: 50px; text-align:center;">
          <i class="hide spotify_player_list_item_play_icon glyphicon glyphicon-play" style="cursor:pointer; cursor:hand;"></i>
          <%= image_tag 'home_page/spinner.gif', class: 'spotify_player_list_item_spinner' %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/music/tracks/_recent_chart_image.html.erb
<div class="sidebar-module">
  <a href="http://www.last.fm/user/<%= Setting['home_page.apis.providers.lastfm.user_name'] %>/tracks">
    <img src="<%= 
      "http://imagegen.last.fm/#{Setting['home_page.apis.providers.lastfm.charts.types.recent_tracks.design']}/" +
      "recenttracks/#{Setting['home_page.apis.providers.lastfm.charts.types.recent_tracks.tracks_count']}/" +
      "#{Setting['home_page.apis.providers.lastfm.user_name']}.gif"
    %>" border="0" />
  </a> 
</div>

app/views/music/videos/index.html.erb
<% content_for :title do %><%= t('music_videos.index.title') %><% end %>

<% if @videos['entries'].none? %>
<p><%= t('music_videos.index.empty_collection') %></p>
<% else %>
  <% @videos['entries'].each do |video| %>
<h5><%= link_to(
  "#{video['artist_name']} – #{video['track_name']} (#{video['status']})", 
  "#{@host}/music/videos/#{video['id']}"
) %> <%= t('general.liked_at') %> <%= DateTime.parse(video['liked_at']).strftime('%d.%m.%Y %H:%M:%S') %></h4>
<p><%= markdown video['url'] %></p>
  <% end %>
<%= will_paginate @pagination, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/music/year_in_reviews/_collection.html.erb
<% if @year_in_reviews['entries'].none? %>
<p><%= t('music_year_in_reviews.index.empty_collection') %></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr class="<%= cycle('odd', 'even') %>">
        <th style="width: 45px"><%= t("general.year") %></th>
        <th style="width: 100px"></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @year_in_reviews['entries'].each do |year_in_review| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td>
          <%= link_to year_in_review['year'], music_year_in_review_path(year_in_review['year']) %>
        </td>
        <td>
          <%= link_to(
            t('music_year_in_reviews.show.top_albums.short_title'), 
            top_albums_music_year_in_review_path(year_in_review['year']) 
          ) %>
        </td>
        <td>
          <%= link_to(
            t('music_year_in_reviews.show.top_songs.short_title'), 
            top_songs_music_year_in_review_path(year_in_review['year']) 
          ) %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <%= will_paginate @pagination, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/music/year_in_reviews/index.html.erb
<% content_for :title do %><%= t('music_year_in_reviews.index.title') %><% end %>

<div id="music_year_in_reviews">
  <%= render partial: 'music/year_in_reviews/collection' %>
</div>

app/views/music/year_in_reviews/show.html.erb
<% content_for :title do %><%= t('music_year_in_reviews.show.title', year: params[:id]) %><% end %>

<ul class="nav nav-pills nav-stacked">
  <li>
    <%= link_to(
      t('music_year_in_reviews.show.top_albums.short_title'), 
      top_albums_music_year_in_review_path(params[:id]) 
    ) %>
  </li>
  <li>
    <%= link_to(
      t('music_year_in_reviews.show.top_songs.short_title'), 
      top_songs_music_year_in_review_path(params[:id]) 
    ) %>
  </li>
</ul>

app/views/music/year_in_reviews/top_albums.html.erb
<% content_for :title do %><%= t('music_year_in_reviews.show.top_albums.title', year: params[:id]) %><% end %>

<% if @albums.none? %>
<p><%= t('music_year_in_reviews.show.top_albums.empty_collection') %></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr class="<%= cycle('odd', 'even') %>">
        <th style="width: 50px; vertical-align:top;"><%= t('general.position') %></th>
        <th style="width: 200px; vertical-align:top;"><%= t('music.general.music_artist.short') %></th>
        <th style="width: 200px; vertical-align:top;"><%= t('general.name') %></th>
        <th style="width: 67px; vertical-align:top;"><%= t('music_year_in_reviews.show.top_track_positions_sum')%></th>
        <th style="width: 300px; vertical-align:top;"><%= t('music_year_in_reviews.show.top_songs.short_title') %></th>
        <th style="width: 50px;"></th>
      </tr>
    </thead>
    <tbody>
    <% @albums.each do |album| %>
      <tr 
        class="spotify_player_list_item <%= cycle('odd', 'even') %>" 
        data-model="Release" data-artist-name="<%= album['artist_name'] %>" data-name="<%= album['release_name'] %>"
      >
        <td><%= album['position'] %></td>
        <td><%= link_to album['artist_name'], "#{@host}/music/artists/#{album['artist_id']}" %></td>
        <td><%= link_to album['release_name'], "#{@host}/music/releases/#{album['release_id']}" %></td>
        <td><%= album['top_track_positions_sum'] %></td>
        <td>
          <%= raw(album['top_tracks'].map do |t| 
            "#{t['position']}. " + link_to(t['track_name'], "#{@host}/music/tracks/#{t['track_id']}")
          end.join(', ')) %>
        </td>
        <td style="width: 50px; text-align:center;">
          <i class="hide spotify_player_list_item_play_icon glyphicon glyphicon-play" style="cursor:pointer; cursor:hand;"></i>
          <%= image_tag 'home_page/spinner.gif', class: 'spotify_player_list_item_spinner' %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <% content_for :document_ready do %>
    window.volontariatHost = "<%= HomePage::ApiProviderHost.new('volontariat', Rails.env).to_s %>";
    new SpotifyPlayerList();
  <% end %>
<% end %>

app/views/music/year_in_reviews/top_songs.html.erb
<% content_for :title do %><%= t('music_year_in_reviews.show.top_songs.title', year: params[:id]) %><% end %>

<% if @songs.none? %>
<p><%= t('music_year_in_reviews.show.top_songs.empty_collection') %></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr class="<%= cycle('odd', 'even') %>">
        <th style="width: 50px; vertical-align:top;"><%= t('general.position') %></th>
        <th style="width: 200px; vertical-align:top;"><%= t('music.general.music_artist.short') %></th>
        <th style="width: 200px; vertical-align:top;"><%= t('general.name') %></th>
        <th style="width: 50px;"></th>
      </tr>
    </thead>
    <tbody>
    <% @songs.each do |song| %>
      <tr 
        class="spotify_player_list_item <%= cycle('odd', 'even') %>" 
        data-model="Track" data-artist-name="<%= song['artist_name'] %>" data-name="<%= song['track_name'] %>"
      >
        <td><%= song['position'] %></td>
        <td><%= link_to song['artist_name'], "#{@host}/music/artists/#{song['artist_id']}" %></td>
        <td><%= link_to song['track_name'], "#{@host}/music/tracks/#{song['track_id']}" %></td>
        <td style="width: 50px; text-align:center;">
          <i class="hide spotify_player_list_item_play_icon glyphicon glyphicon-play" style="cursor:pointer; cursor:hand;"></i>
          <%= image_tag 'home_page/spinner.gif', class: 'spotify_player_list_item_spinner' %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <% content_for :document_ready do %>
    window.volontariatHost = "<%= HomePage::ApiProviderHost.new('volontariat', Rails.env).to_s %>";
    new SpotifyPlayerList();
  <% end %>
<% end %>

app/views/settings/plugins/home_page_music/_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="heading<%= index + 1 %>">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#settings_accordion" href="#home_page_music_settings" aria-expanded="true" aria-controls="home_page_music_settings">
        <%= t('settings.index.plugins.home_page_music.index.title') %>
      </a>
    </h4>
  </div>
  
  <div id="home_page_music_settings" class="panel-collapse collapse<% if index == 0 %> in<% end %>" role="tabpanel" aria-labelledby="heading<%= index + 1 %>">
    <div class="panel-body">
      <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#home_page_music_settings_general" aria-controls="home_page_music_settings_general" role="tab" data-toggle="tab">
              <%= t('settings.index.plugins.home_page.tabs.general.title') %>
            </a>
          </li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="home_page_music_settings_general">
            <p>
              <%= t('general.todo') %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>